oc new-app --name start --image=quay.io/rh_ee_sshirodk/wordmesh:v1 --labels sidecar.istio.io/inject=true
oc new-app --name letter-a --image=quay.io/rh_ee_sshirodk/wordmesh:v1  --labels sidecar.istio.io/inject=true
oc new-app --name letter-b --image=quay.io/rh_ee_sshirodk/wordmesh:v1  --labels sidecar.istio.io/inject=true
oc new-app --name letter-c --image=quay.io/rh_ee_sshirodk/wordmesh:v1  --labels sidecar.istio.io/inject=true
oc new-app --name letter-d --image=quay.io/rh_ee_sshirodk/wordmesh:v1  --labels sidecar.istio.io/inject=true
oc new-app --name letter-e --image=quay.io/rh_ee_sshirodk/wordmesh:v1  --labels sidecar.istio.io/inject=true
oc new-app --name letter-f --image=quay.io/rh_ee_sshirodk/wordmesh:v1  --labels sidecar.istio.io/inject=true
oc new-app --name letter-g --image=quay.io/rh_ee_sshirodk/wordmesh:v1  --labels sidecar.istio.io/inject=true
oc new-app --name letter-h --image=quay.io/rh_ee_sshirodk/wordmesh:v1  --labels sidecar.istio.io/inject=true
oc new-app --name letter-i --image=quay.io/rh_ee_sshirodk/wordmesh:v1  --labels sidecar.istio.io/inject=true
oc new-app --name letter-j --image=quay.io/rh_ee_sshirodk/wordmesh:v1  --labels sidecar.istio.io/inject=true
oc new-app --name letter-k --image=quay.io/rh_ee_sshirodk/wordmesh:v1  --labels sidecar.istio.io/inject=true
oc new-app --name letter-l --image=quay.io/rh_ee_sshirodk/wordmesh:v1  --labels sidecar.istio.io/inject=true
oc new-app --name letter-m --image=quay.io/rh_ee_sshirodk/wordmesh:v1  --labels sidecar.istio.io/inject=true
oc new-app --name letter-n --image=quay.io/rh_ee_sshirodk/wordmesh:v1  --labels sidecar.istio.io/inject=true
oc new-app --name letter-o --image=quay.io/rh_ee_sshirodk/wordmesh:v1  --labels sidecar.istio.io/inject=true
oc new-app --name letter-p --image=quay.io/rh_ee_sshirodk/wordmesh:v1  --labels sidecar.istio.io/inject=true
oc new-app --name letter-q --image=quay.io/rh_ee_sshirodk/wordmesh:v1  --labels sidecar.istio.io/inject=true
oc new-app --name letter-r --image=quay.io/rh_ee_sshirodk/wordmesh:v1  --labels sidecar.istio.io/inject=true
oc new-app --name letter-s --image=quay.io/rh_ee_sshirodk/wordmesh:v1  --labels sidecar.istio.io/inject=true
oc new-app --name letter-t --image=quay.io/rh_ee_sshirodk/wordmesh:v1  --labels sidecar.istio.io/inject=true
oc new-app --name letter-u --image=quay.io/rh_ee_sshirodk/wordmesh:v1  --labels sidecar.istio.io/inject=true
oc new-app --name letter-v --image=quay.io/rh_ee_sshirodk/wordmesh:v1  --labels sidecar.istio.io/inject=true
oc new-app --name letter-w --image=quay.io/rh_ee_sshirodk/wordmesh:v1  --labels sidecar.istio.io/inject=true
oc new-app --name letter-x --image=quay.io/rh_ee_sshirodk/wordmesh:v1  --labels sidecar.istio.io/inject=true
oc new-app --name letter-y --image=quay.io/rh_ee_sshirodk/wordmesh:v1  --labels sidecar.istio.io/inject=true
oc new-app --name letter-z --image=quay.io/rh_ee_sshirodk/wordmesh:v1  --labels sidecar.istio.io/inject=true
oc new-app --name end --image=quay.io/rh_ee_sshirodk/wordmesh:v1  --labels sidecar.istio.io/inject=true
