kind: BuildConfig
apiVersion: build.openshift.io/v1
metadata:
  name: wordmesh-quarkus-git
spec:
  output:
    to:
      kind: DockerImage
      name: 'quay.io/rh_ee_sshirodk/wordmesh:v1'
  strategy:
    type: Source
    sourceStrategy:
      from:
        kind: ImageStreamTag
        namespace: openshift
        name: 'java:openjdk-17-ubi8'
  source:
    type: Git
    git:
      uri: 'https://github.com/shirodkar/wordmesh-quarkus.git'
    contextDir: /
