kind: Service
apiVersion: v1
metadata:
  name: wordmesh
  annotations:
    sidecar.istio.io/inject: 'true'
spec:
  ports:
    - name: 8080-tcp
      protocol: TCP
      port: 8080
      targetPort: 8080
  type: ClusterIP
  selector:
    app: wordmesh